[application]
name = "edgeray-app"
default_platform = "desktop"
out_dir = "dist"
asset_dir = "assets"

[bundle]
identifier = "com.jrad.edgeray-app"
publisher = "EdgeRay"

[web.app]
title = "EdgeRay"
base_path = ""

[web.resource.dev]
style = ["/styles.css"]

[web.resource.release]
style = ["/styles.css"]

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]
index_on_404 = true
